// <auto-generated />
namespace Caps.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class AlterContentParts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterContentParts));
        
        string IMigrationMetadata.Id
        {
            get { return "201311201740416_AlterContentParts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
